### ISSUE TITLE
Data loss with wiko extractor

### ISSUE THREAD

**Issue by CoumbaMboup** [PDL-2019-2020-GR8/PDL_2018_2019_GR6#3]
The extractor wiki considers the colored cells as empty even if there are values

**Comment by mrothniel** [comment]
It is not because of the color that he ignores or that he cannot take the information.The ignored information is in braces within the wiki code to write to a table.Peculiar recover well the table of the page!!!When parsing by Mylyn he just ignores it's info between accolade in the "wiktable sortable"
Exemple : {| class="wikitable sortable" style="font-size: 80%; text-align: center; width: auto;"
|-
! Concept
! memory efficiency
! multiple type document
! small-sized content
! use simultaneously different application
! easy to view all document labels of same type document
! Applications
|-
! [[Single document interface]]
| {{no}}
| {{yes}}
| {{no}}
| {{no}}
| depends on Window System
| [[Inkscape]]
|}
the csv file generated by the wikiExtractor will be the following:
![CSV](https://user-images.githubusercontent.com/45700033/67249800-3df94300-f469-11e9-85ce-9f6788d7233c.PNG)
Information between the braces "{{ ... }}" is not displayed!!!

**Comment by CoumbaMboup** [comment]
finally to solve the data loss we used Bliki which allows to extract more data than Mylyn
